

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.07 at 02:49:13 PM IST 
//

package in.gov.uidai.impl.dataportal.enrl_search_request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Relation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Relation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rel-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rel-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rel-local-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rel-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rel-id-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Relation", propOrder = {
    "relType",
    "relName",
    "relLocalName",
    "relId",
    "relIdType"
})
public class Relation {

    @XmlElement(name = "rel-type", required = true)
    protected String relType;
    @XmlElement(name = "rel-name", required = true)
    protected String relName;
    @XmlElement(name = "rel-local-name", required = true)
    protected String relLocalName;
    @XmlElement(name = "rel-id", required = true)
    protected String relId;
    @XmlElement(name = "rel-id-type", required = true)
    protected String relIdType;

    /**
     * Gets the value of the relType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelType() {
        return relType;
    }

    /**
     * Sets the value of the relType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelType(String value) {
        this.relType = value;
    }

    /**
     * Gets the value of the relName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelName() {
        return relName;
    }

    /**
     * Sets the value of the relName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelName(String value) {
        this.relName = value;
    }

    /**
     * Gets the value of the relLocalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelLocalName() {
        return relLocalName;
    }

    /**
     * Sets the value of the relLocalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelLocalName(String value) {
        this.relLocalName = value;
    }

    /**
     * Gets the value of the relId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelId() {
        return relId;
    }

    /**
     * Sets the value of the relId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelId(String value) {
        this.relId = value;
    }

    /**
     * Gets the value of the relIdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelIdType() {
        return relIdType;
    }

    /**
     * Sets the value of the relIdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelIdType(String value) {
        this.relIdType = value;
    }

}
